import { hashSync } from "bcrypt-ts-edge";

const sampleData = {
  products: [
    {
      name: "Sauvage Dior",
      slug: "sauvage-dior",
      category: "For Him",
      brand: "Dior",
      description:
        "A radically fresh composition, dictated by a name that has the ring of a manifesto.",
      images: ["/product.jpg"],
      variants: {
        create: [
          { size: "30ml", type: "Perfume", price: "75.00" },
          { size: "50ml", type: "Perfume", price: "95.00" },
          { size: "100ml", type: "Perfume", price: "120.00" },
          { size: "Standard", type: "Shower Gel", price: "45.00" },
          { size: "Standard", type: "Body Lotion", price: "35.00" },
          { size: "Standard", type: "Body Butter", price: "35.00" },
          { size: "Standard", type: "Body Youghurt", price: "35.00" },
          { size: "Standard", type: "Body Scrab", price: "35.00" },
          { size: "Standard", type: "Body Lotion", price: "35.00" },
          { size: "Standard", type: "Deodorant", price: "35.00" },
          { size: "Standard", type: "Body Oil", price: "35.00" },
          {
            size: "Standard",
            type: "Body Oil Glitter Shimmer",
            price: "35.00",
          },
          { size: "Standard", type: "Body Mist", price: "35.00" },
          { size: "Standard", type: "Beard Oil", price: "35.00" },
          { size: "Standard", type: "Car Fragrance", price: "35.00" },
        ],
      },
    },
    {
      name: "Libre Le Parfum",
      slug: "libre-le-parfum",
      category: "For Her",
      brand: "YSL",
      description: "The freedom to live everything with excess.",
      images: ["/product.jpg"],
      variants: {
        create: [
          { size: "30ml", type: "Perfume", price: "75.00" },
          { size: "50ml", type: "Perfume", price: "95.00" },
          { size: "100ml", type: "Perfume", price: "120.00" },
          { size: "Standard", type: "Shower Gel", price: "45.00" },
          { size: "Standard", type: "Body Lotion", price: "35.00" },
          { size: "Standard", type: "Body Butter", price: "35.00" },
          { size: "Standard", type: "Body Youghurt", price: "35.00" },
          { size: "Standard", type: "Body Scrab", price: "35.00" },
          { size: "Standard", type: "Body Lotion", price: "35.00" },
          { size: "Standard", type: "Deodorant", price: "35.00" },
          { size: "Standard", type: "Body Oil", price: "35.00" },
          {
            size: "Standard",
            type: "Body Oil Glitter Shimmer",
            price: "35.00",
          },
          { size: "Standard", type: "Body Mist", price: "35.00" },
          { size: "Standard", type: "Beard Oil", price: "35.00" },
          { size: "Standard", type: "Car Fragrance", price: "35.00" },
        ],
      },
    },
    {
      name: "Baccarat Rouge 540",
      slug: "baccarat-rouge-540",
      category: "Niche",
      brand: "Maison Francis Kurkdjian",
      description:
        "Luminous and sophisticated, Baccarat Rouge 540 lays on the skin like an amber, floral and woody breeze.",
      images: ["/product.jpg"],
      variants: {
        create: [
          { size: "30ml", type: "Perfume", price: "75.00" },
          { size: "50ml", type: "Perfume", price: "95.00" },
          { size: "100ml", type: "Perfume", price: "120.00" },
          { size: "Standard", type: "Shower Gel", price: "45.00" },
          { size: "Standard", type: "Body Lotion", price: "35.00" },
          { size: "Standard", type: "Body Butter", price: "35.00" },
          { size: "Standard", type: "Body Youghurt", price: "35.00" },
          { size: "Standard", type: "Body Scrab", price: "35.00" },
          { size: "Standard", type: "Body Lotion", price: "35.00" },
          { size: "Standard", type: "Deodorant", price: "35.00" },
          { size: "Standard", type: "Body Oil", price: "35.00" },
          {
            size: "Standard",
            type: "Body Oil Glitter Shimmer",
            price: "35.00",
          },
          { size: "Standard", type: "Body Mist", price: "35.00" },
          { size: "Standard", type: "Beard Oil", price: "35.00" },
          { size: "Standard", type: "Car Fragrance", price: "35.00" },
        ],
      },
    },
    {
      name: "Blue de Chanel",
      slug: "blue-de-chanel",
      category: "For Him",
      brand: "Chanel",
      description:
        "A woody, aromatic fragrance for the man who defies convention.",
      images: ["/product.jpg"],
      variants: {
        create: [
          { size: "30ml", type: "Perfume", price: "75.00" },
          { size: "50ml", type: "Perfume", price: "95.00" },
          { size: "100ml", type: "Perfume", price: "120.00" },
          { size: "Standard", type: "Shower Gel", price: "45.00" },
          { size: "Standard", type: "Body Lotion", price: "35.00" },
          { size: "Standard", type: "Body Butter", price: "35.00" },
          { size: "Standard", type: "Body Youghurt", price: "35.00" },
          { size: "Standard", type: "Body Scrab", price: "35.00" },
          { size: "Standard", type: "Body Lotion", price: "35.00" },
          { size: "Standard", type: "Deodorant", price: "35.00" },
          { size: "Standard", type: "Body Oil", price: "35.00" },
          {
            size: "Standard",
            type: "Body Oil Glitter Shimmer",
            price: "35.00",
          },
          { size: "Standard", type: "Body Mist", price: "35.00" },
          { size: "Standard", type: "Beard Oil", price: "35.00" },
          { size: "Standard", type: "Car Fragrance", price: "35.00" },
        ],
      },
    },
    {
      name: "Eros",
      slug: "versace-eros",
      category: "For Him",
      brand: "Versace",
      description: "Love, passion, beauty and desire.",
      images: ["/product.jpg"],
      variants: {
        create: [
          { size: "30ml", type: "Perfume", price: "75.00" },
          { size: "50ml", type: "Perfume", price: "95.00" },
          { size: "100ml", type: "Perfume", price: "120.00" },
          { size: "Standard", type: "Shower Gel", price: "45.00" },
          { size: "Standard", type: "Body Lotion", price: "35.00" },
          { size: "Standard", type: "Body Butter", price: "35.00" },
          { size: "Standard", type: "Body Youghurt", price: "35.00" },
          { size: "Standard", type: "Body Scrab", price: "35.00" },
          { size: "Standard", type: "Body Lotion", price: "35.00" },
          { size: "Standard", type: "Deodorant", price: "35.00" },
          { size: "Standard", type: "Body Oil", price: "35.00" },
          {
            size: "Standard",
            type: "Body Oil Glitter Shimmer",
            price: "35.00",
          },
          { size: "Standard", type: "Body Mist", price: "35.00" },
          { size: "Standard", type: "Beard Oil", price: "35.00" },
          { size: "Standard", type: "Car Fragrance", price: "35.00" },
        ],
      },
    },
  ],
  users: [
    {
      name: "Admin User",
      email: "admin@example.com",
      password: hashSync("123456", 10),
      role: "admin",
    },
    {
      name: "Aggelos",
      email: "akermezo@yahoo.com",
      password: hashSync("123456", 10),
      role: "admin",
    },
    {
      name: "John Doe",
      email: "user@example.com",
      password: hashSync("123456", 10),
      role: "user",
    },
  ],
};

export default sampleData;
